# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5d3806cce573da2e8b91d46a29fac9070b99fdf3b6945fc6c030c5c9fbdbd1e27da16a1023d87dab18f2ac8acab47cef45da558f7639d58edf075bd7fe0bff9

test:
  secret_key_base: 7f6513b77c50f23ba6420a6ae9f29c341a4ae57e02e3204ffbe05bb8b21728e42334806c0fdbe56d0a07bd9bb0c0c0fda8a8e7149fc1910fcd6b62784810def4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
